module.exports = {
  "PREFIX": ".",
  "AUTO_READ_STATUS": false,
  "MODE": "public",
  "OWNER_NUMBER": "94717775628",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": false,
  "WELCOME": false,
  "DELMSG": "public",
  "MNAME": "𝗫PRO𝚅𝙴𝚁𝙲𝙴  〽️ᗪ",
  "ANTI_BAD": [],
  "ANTI_BOT": [],
  "ANTI_LINK": [],
  "ANTI_CALL": false,
  "ANTI_DELETE": false,
  "ALWAYS_ONLINE": true,
  "MOROCCOBLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "MR.RASHMIKA",
  "NEWS_JID": false,
  "MOVIE_JID": false,
  "ANIME_JID": false,
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "FOOTER": "> 𝗫PRO𝚅𝙴𝚁𝙲𝙴  〽️ᗪ\n> `Developed by Mr. Rashmika`",
  "OWNER_REACT": false,
  "EMOJI": "🏷",
  "AI_MODE": false,
  "AI": "Boy",
  "BANNED": [],
  "SUDO": [
    "94717775628"
  ],
  "LANG": "EN",
  "isPremium": false
};